// <auto-generated />
namespace SpeakerNet.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Votes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Votes));
        
        string IMigrationMetadata.Id
        {
            get { return "201302071708052_Votes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
