//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.372
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakerNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpeakertNetStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpeakertNetStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeakerNet.Properties.SpeakertNetStrings", typeof(SpeakertNetStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadt.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Address_Country {
            get {
                return ResourceManager.GetString("Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string Address_Street {
            get {
                return ResourceManager.GetString("Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string Address_ZipCode {
            get {
                return ResourceManager.GetString("Address_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Contact_EMail {
            get {
                return ResourceManager.GetString("Contact_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefax.
        /// </summary>
        public static string Contact_Fax {
            get {
                return ResourceManager.GetString("Contact_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Contact_Homepage {
            get {
                return ResourceManager.GetString("Contact_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Contact_Phone {
            get {
                return ResourceManager.GetString("Contact_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ResourceName: .
        /// </summary>
        public static string Exception_MissingResourceName {
            get {
                return ResourceManager.GetString("Exception_MissingResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen {0}!.
        /// </summary>
        public static string LogOn_Welcome {
            get {
                return ResourceManager.GetString("LogOn_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltungen.
        /// </summary>
        public static string Navigation_Events {
            get {
                return ResourceManager.GetString("Navigation_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        public static string Navigation_Home {
            get {
                return ResourceManager.GetString("Navigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string Navigation_Imprint {
            get {
                return ResourceManager.GetString("Navigation_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string Navigation_LogOff {
            get {
                return ResourceManager.GetString("Navigation_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Navigation_LogOn {
            get {
                return ResourceManager.GetString("Navigation_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Navigation_Sessions {
            get {
                return ResourceManager.GetString("Navigation_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprecher.
        /// </summary>
        public static string Navigation_Speakers {
            get {
                return ResourceManager.GetString("Navigation_Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minuten.
        /// </summary>
        public static string Session_1_Minutes {
            get {
                return ResourceManager.GetString("Session_1_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Session_Abstract {
            get {
                return ResourceManager.GetString("Session_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        public static string Session_Duration {
            get {
                return ResourceManager.GetString("Session_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung.
        /// </summary>
        public static string Session_Event {
            get {
                return ResourceManager.GetString("Session_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Session_Level {
            get {
                return ResourceManager.GetString("Session_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überblick für Neulinge.
        /// </summary>
        public static string Session_Level100 {
            get {
                return ResourceManager.GetString("Session_Level100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfänger.
        /// </summary>
        public static string Session_Level200 {
            get {
                return ResourceManager.GetString("Session_Level200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortgeschritten.
        /// </summary>
        public static string Session_Level300 {
            get {
                return ResourceManager.GetString("Session_Level300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dive.
        /// </summary>
        public static string Session_Level400 {
            get {
                return ResourceManager.GetString("Session_Level400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Session_Name {
            get {
                return ResourceManager.GetString("Session_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprecher.
        /// </summary>
        public static string Session_Speaker {
            get {
                return ResourceManager.GetString("Session_Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessionvorschlag.
        /// </summary>
        public static string Session_Suggestion {
            get {
                return ResourceManager.GetString("Session_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biographie.
        /// </summary>
        public static string Speaker_Biography {
            get {
                return ResourceManager.GetString("Speaker_Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Speaker_Company {
            get {
                return ResourceManager.GetString("Speaker_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Sprecher anlegen.
        /// </summary>
        public static string Speaker_CreateNewSpeaker {
            get {
                return ResourceManager.GetString("Speaker_CreateNewSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten von {0} {1}.
        /// </summary>
        public static string Speaker_Edit_of {
            get {
                return ResourceManager.GetString("Speaker_Edit_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisherige Veranstaltungen.
        /// </summary>
        public static string Speaker_Engagement {
            get {
                return ResourceManager.GetString("Speaker_Engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string Speaker_FirstName {
            get {
                return ResourceManager.GetString("Speaker_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string Speaker_Help {
            get {
                return ResourceManager.GetString("Speaker_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string Speaker_LastName {
            get {
                return ResourceManager.GetString("Speaker_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Speaker_Name {
            get {
                return ResourceManager.GetString("Speaker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anrede.
        /// </summary>
        public static string Speaker_Salutation {
            get {
                return ResourceManager.GetString("Speaker_Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprecher-Sessions.
        /// </summary>
        public static string Speaker_SessionList {
            get {
                return ResourceManager.GetString("Speaker_SessionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Speaker_Sessions {
            get {
                return ResourceManager.GetString("Speaker_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Sprecher.
        /// </summary>
        public static string Speaker_SpeakerList {
            get {
                return ResourceManager.GetString("Speaker_SpeakerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mögliche Themen.
        /// </summary>
        public static string Speaker_Topics {
            get {
                return ResourceManager.GetString("Speaker_Topics", resourceCulture);
            }
        }
    }
}
