//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakerNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpeakertNetStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpeakertNetStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeakerNet.Properties.SpeakertNetStrings", typeof(SpeakertNetStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadt.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Address_Country {
            get {
                return ResourceManager.GetString("Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string Address_Street {
            get {
                return ResourceManager.GetString("Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string Address_ZipCode {
            get {
                return ResourceManager.GetString("Address_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Contact_EMail {
            get {
                return ResourceManager.GetString("Contact_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefax.
        /// </summary>
        public static string Contact_Fax {
            get {
                return ResourceManager.GetString("Contact_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Contact_Homepage {
            get {
                return ResourceManager.GetString("Contact_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Contact_Phone {
            get {
                return ResourceManager.GetString("Contact_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biographie.
        /// </summary>
        public static string Speaker_Biographx {
            get {
                return ResourceManager.GetString("Speaker_Biographx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Speaker_Company {
            get {
                return ResourceManager.GetString("Speaker_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisherige Veranstaltungen.
        /// </summary>
        public static string Speaker_Engagement {
            get {
                return ResourceManager.GetString("Speaker_Engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string Speaker_FirstName {
            get {
                return ResourceManager.GetString("Speaker_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string Speaker_LastName {
            get {
                return ResourceManager.GetString("Speaker_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Speaker_Name {
            get {
                return ResourceManager.GetString("Speaker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anrede.
        /// </summary>
        public static string Speaker_Salutation {
            get {
                return ResourceManager.GetString("Speaker_Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mögliche Themen.
        /// </summary>
        public static string Speaker_Topics {
            get {
                return ResourceManager.GetString("Speaker_Topics", resourceCulture);
            }
        }
    }
}
